import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { cx } from "@/shared/utils";

const dos = localFont({
  src: "../shared/assets/fonts/ModernDOS8x16.ttf",
  variable: "--font-dos",
  fallback: ["Courier New", "Courier", "monospace"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="flex min-h-screen items-center justify-center bg-secondary"
    >
      <body
        className={cx(
          "flex h-full min-h-screen w-full max-w-screen-xl flex-col",
          dos.className,
        )}
      >
        {children}
      </body>
    </html>
  );
}
